###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "admin.admin@admin.fr",
    "password": "123456Az!"
}

###
@TOKEN=token

###
GET http://localhost:5001/api/users
Authorization: Bearer {{TOKEN}}


###
POST http://localhost:5001/api/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "test.test@test.fr",
    "name": "Test",
    "password": "beedemo"
}

###
PUT http://localhost:5001/api/users/943602075
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "test2.test2@test2.fr"
}


###
DELETE http://localhost:5001/api/users/943602075
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###
GET http://localhost:5001/api/barbucues
Authorization: Bearer {{TOKEN}}

###

POST http://localhost:5001/api/barbucues
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "Test",
    "place": "Toulouse",
    "date": "2023-04-27 18:30:00"
}


###

PUT http://localhost:5001/api/barbucues/362094319
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "Test 2",
    "place": "Toulouse 2",
    "date": "2023-04-27 18:45:00"
}


###
DELETE  http://localhost:5001/api/barbucues/362094319
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###
POST http://localhost:5001/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

