###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "victor.cyprien@limayrac.fr",
    "password": "beedemo"
}

###
@TOKEN=token
###
GET http://localhost:5001/api/users
Authorization: Bearer {{TOKEN}}


###
POST http://localhost:5001/api/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "test.test@test.fr",
    "name": "Test",
    "password": "beedemo"
}

###
PUT http://localhost:5001/api/users/1035547759
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "victor.cyprien@limayrac.fr"
}


###
DELETE http://localhost:5001/api/users/644277296
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


###
POST http://localhost:5001/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

